### ISSUE TITLE
Remove teachparttime fodler

### ISSUE THREAD

**Issue by davidgatti** [adbloomandrew/teachparttime#1]
Hi @Serhii-Hulko,

I just saw that you added a folder to this repo in the master branch. I understand that you wanted to add the CSS and images to the project, but this is not the way of going about it :) 

If we want to work together then the flow must go as follow to keep some sanity in place :) 

- the master branch has only code tested and for the public - normally I would lock the master branch from accepting commits without a PR but since I'm not an admin in this Org, I can't do that. The best approach is just to agree what to do and what not to do.
- the development branch is the branch where as developers we develop our code, and this is the place where all the latest code goes. 
- If you want to add all the assets for the project, the ideal approach would be to branch out from the development branch. Call the new branch "new-assets", add all that is needed, commit the changes, and open a PR where you ask to merge your new branch in to development. This way I'm aware of what is changing. 

Regarding the folder structure of this project, you want to add all the assets:

- CSS
- Images

inside this folder: https://github.com/adbloomandrew/teachparttime/tree/master/_input/assets

I hope this helps and if you have any questions regarding what I wrote please don't hesitate to reply to this Issue, and I'll try to answer you as best as I can.

**Comment by Serhii-Hulko** [comment]
Hi, @davidgatti 
Completely agree with you :) you have described principles of git flow ;) Let's do it in this way. So, should I replace my project (`teachparttime` folder) to another repo in your organisation or it can be placed in my account as that was before? After making changing in my project, I'll provide new assets and markup in PR to this repo

**Comment by Serhii-Hulko** [comment]
I have removed `teachparttime` folder from the project

**Comment by davidgatti** [comment]
This is not my organization :) this is `adBloom` organization, and yes ideally you want to create a new repo in the org.
