### ISSUE TITLE
Styling the new Thank You pages

### ISSUE THREAD

**Issue by davidgatti** [adbloomandrew/teachparttime#39]
@Serhii-Hulko I did some new stuff for you to style and reorganized the repo, and this are the file to look at:

- thankyou_no.hjs
- thankyou_skip.hjs

I also merged the `heroku` branch in to the `development` to start consolidating the project. You still work on your style in the `heroku-style`. Once the main work is done, we will get rid of it, and we will switch in to make a new branch for each issue from the `development` one. 

We did not do it right now to just go faster, but once the bulk fo the work is done, to stay organized it will be much better if we o a branch per issue, and work on that one branch together. I do what I have to do, and then you take over the branch and style it, and then we merge it in to the development one.

**Comment by Serhii-Hulko** [comment]
@davidgatti  Ok, got it. Thank you for explanation :)

**Comment by Serhii-Hulko** [comment]
@davidgatti 
“SKIP FOR NOW” -> thankyou_skip
“SUCCESSFUL APPLICANT” -> thankyou
“FAIL” -> thankyou_no
did i understand correctly?

**Comment by davidgatti** [comment]
I believe so :)

**Comment by Serhii-Hulko** [comment]
@davidgatti Check my PR please :)

**Comment by davidgatti** [comment]
Done :) and merged, all looks good.
