### ISSUE TITLE
Style the session restoration page

### ISSUE THREAD

**Issue by davidgatti** [adbloomandrew/teachparttime#7]
@Serhii-Hulko one thing that you could do if Andrew will want is to style the [restore.html](https://github.com/adbloomandrew/teachparttime/blob/styling/_input/views/restore.html) page. This page loads the data from Airtable and restores the session. On slow connections this page might show as an empty page. I added a small txt. But for sure you could style it, and a spinner maybe? 

Ask @aabony for sure what to do.

/cc: @aabony

**Comment by aabony** [comment]
yes @Serhii-Hulko that would be cool, maybe something that says "loading" while the page loads? 

https://ihatetomatoes.net/create-custom-preloading-screen/

**Comment by davidgatti** [comment]
My small advice: I would not recommend linking an asset like GIF or JPG, rather base64 encode it and add it directly to the CSS. This way the asset will have time to be displayed.

This page is super quick, and only will be visible on slow connection but even then it should be failry, fast, since the delay will come from airtable API call.

So if you ant to have a chance to show something nice, embed as much as possible in the HTML or CSS.

**Comment by Serhii-Hulko** [comment]
Thanks :) I'll add spinner based on css only

**Comment by davidgatti** [comment]
I see on the site that there is an animation so I'm assuming this issue is done.
